### ISSUE TITLE
System doesn't stop sending notification mail when the event has been ended

### ISSUE THREAD

**Issue by tlle14** [OpenPaaS-Suite/esn-frontend-calendar#232] opened 2020-10-26 03:42 UTC
# Precondition
Recurrence event has a reminder

# Actual Result
The attendee doesn't respond to the event. When the event ended, the system continues sending notification emails. 

For example, Attendee has been invited to a recurrence event with 2 children, reminder is 15 mins before. 
![image](https://user-images.githubusercontent.com/69950655/97130783-f04aa100-1774-11eb-91c4-3357e68063a2.png)

But the Attendee still receives the notification mail even the event has ended 
![image](https://user-images.githubusercontent.com/69950655/97130924-5c2d0980-1775-11eb-87d0-2bc16ee3a643.png)

# Expected Result
- Attendee shouldn't receive the notification about the event he doesn't respond to (@huy-ta please confirm this behavior)
- The notification should be stopped when the event ended.

# Environment
DEV environment

**Comment by rezk2ll** [comment] 2021-02-25 16:10
duplicate of https://app.zenhub.com/workspaces/ft---calendar--contacts-dev-5ff3db9704b1b3001295e51f/issues/openpaas-suite/esn-frontend-calendar/358

**Closed by rezk2ll** 2021-02-25 16:10 UTC
Labels: bug, major
