### ISSUE TITLE
Event time jumps back to previous time after update

### ISSUE THREAD

**Issue by hantt12** [OpenPaaS-Suite/esn-frontend-calendar#230] opened 2020-10-23 09:28 UTC
Update event's datetime by drag&drop

=> event jumps to previous time before jumping to new time

![Peek 2020-10-23 16-25](https://user-images.githubusercontent.com/53081477/96987062-b008da00-154c-11eb-8b71-1c134ba58e63.gif)

**Comment by pbson** [comment] 2020-12-02 07:15
@hantt12 @huy-ta Could you please have a look again at this issue. I can't be able to reproduce it 
![test](https://user-images.githubusercontent.com/32195667/100840573-ac9c3300-34a8-11eb-9937-f613085a9e94.gif)

**Comment by huy-ta** [comment] 2020-12-02 07:39
Yes I can't reproduce it also. I'll close this for the time being.

**Closed by huy-ta** 2020-12-02 07:39 UTC
Labels: Minor, UX/UI, bug
