### ISSUE TITLE
As a User, I want to be able to remove event I haven't organized from my calendar

### ISSUE THREAD

**Issue by renaudboyer** [OpenPaaS-Suite/esn-frontend-calendar#284] opened 2020-11-25 09:56 UTC
As a User, I want to be able to remove event I haven't organized from my calendar.

For now, the only way to remove events from calendar is to decline them and use "Hide declined option" in calendar.

It'll be useful in these cases:

* Remove unwanted event or uninteresting one
* Keep displaying declined event and remove specific ones
* Delete orphans events

Features hints:

* Event form should have a delete button to remove the event from the user calendar.
* Delete will remove event from the user's calendar only
* Delete should propose to remove whole series in case of recurring event

NOTES: 

* Organizer won't be notified if user remove event
* If organizer does significant changes on the event, user will notified and have the event back.

**Comment by rezk2ll** [comment] 2020-12-02 06:36
duplicate of https://github.com/OpenPaaS-Suite/esn-frontend-calendar/issues/309

**Closed by rezk2ll** 2020-12-02 06:36 UTC
Labels: enhancement, needs BA checking
